// Auto-generated from index.json - do not edit
const APP_DATA = {
  version: '1.0',
  lastUpdated: '2026-01-27T10:17:46.640Z',
  applications: [
    {
      id: '2026-01-27-asana-product-owner-revenue-technology',
      company: 'Asana',
      role: 'Product Owner, Revenue Technology',
      status: 'applied',
      applied: '2026-01-27',
      atsScore: 72,
      location: 'Vancouver, BC (Hybrid)',
      url: 'https://www.linkedin.com/jobs/view/4355221148/',
    },
    {
      id: '2026-01-27-insight-global-product-owner',
      company: 'Insight Global',
      role: 'Product Owner',
      status: 'applied',
      applied: '2026-01-27',
      atsScore: 69,
      location: 'Toronto, ON (Hybrid)',
      url: 'https://www.linkedin.com/jobs/view/4365905105/',
    },
    {
      id: '2026-01-27-insight-global-product-owner-lead-ba',
      company: 'Insight Global',
      role: 'Product Owner/Lead BA',
      status: 'saved',
      applied: null,
      atsScore: 78,
      location: 'Toronto, ON (Hybrid)',
      url: 'https://www.linkedin.com/jobs/view/4361979734/',
    },
    {
      id: '2026-01-27-mufg-investor-services-director-it-technical-data-product-owner',
      company: 'MUFG Investor Services',
      role: 'Director IT Technical Data Product Owner',
      status: 'saved',
      applied: null,
      atsScore: 93,
      location: 'Toronto, ON (Hybrid)',
      url: 'https://www.linkedin.com/jobs/view/4329655793/',
    },
    {
      id: '2026-01-27-viralconvert-operational-po-delivery-lead',
      company: 'ViralConvert',
      role: 'Operational Product Owner / Delivery Lead',
      status: 'applied',
      applied: '2026-01-27',
      atsScore: null,
      location: 'Lund, Sweden (On-site)',
      url: 'https://www.linkedin.com/jobs/view/4366233398/',
    },
    {
      id: '2026-01-27-asenium-consulting-product-owner-ai-chatbot',
      company: 'Asenium Consulting',
      role: 'Product Owner - AI Chatbot',
      status: 'applied',
      applied: null,
      location: 'European Union (Remote)',
      url: 'https://www.linkedin.com/jobs/view/4362334087/',
    },
  ],
  stats: {
    total: 6,
    saved: 2,
    applied: 4,
    interviewing: 0,
    rejected: 0,
    withdrawn: 0,
    offer: 0,
  },
}
